name: 'Get Version'
description: 'Get version from tag or input'
inputs:
  version:
    description: 'Version to release'
    required: true
outputs:
  version:
    description: 'Version based on tag or input'
    value: ${{ inputs.version }}